// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT5BBNA-Wp-l2tU4aG7ibDBQcRkgFJ6-w',
    appId: '1:757658133018:web:94d9c4aba3c057f7b667a3',
    messagingSenderId: '757658133018',
    projectId: 'audiostuido',
    authDomain: 'audiostuido.firebaseapp.com',
    storageBucket: 'audiostuido.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApr9ux7WLSkcN7n0qFfo6YeOMbCZtzeaM',
    appId: '1:757658133018:android:68b16c14dc6aaabab667a3',
    messagingSenderId: '757658133018',
    projectId: 'audiostuido',
    storageBucket: 'audiostuido.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7AilXT9MkcD2FJ-R2LsD8aUV8yklhJy8',
    appId: '1:757658133018:ios:d8f8feedf03856e6b667a3',
    messagingSenderId: '757658133018',
    projectId: 'audiostuido',
    storageBucket: 'audiostuido.appspot.com',
    iosBundleId: 'com.example.audioStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7AilXT9MkcD2FJ-R2LsD8aUV8yklhJy8',
    appId: '1:757658133018:ios:686e4a7ed63be868b667a3',
    messagingSenderId: '757658133018',
    projectId: 'audiostuido',
    storageBucket: 'audiostuido.appspot.com',
    iosBundleId: 'com.example.audioStudio.RunnerTests',
  );
}
